services:
  db:
    image: postgres:15-alpine
    container_name: pr_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pr_password
      POSTGRES_DB: pr_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pr_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  integration-tests:
    profiles: ["test"]
    image: golang:1.25-alpine
    container_name: pr_management_integration_tests
    working_dir: /go/src/app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/go/src/app
    environment:
      INTEGRATION_DB_URL: "postgres://postgres:pr_password@db:5432/pr_test_db?sslmode=disable"
    command: >
      sh -c "
        set -e;
        apk add --no-cache postgresql-client >/dev/null 2>&1;
        echo '⏳ Waiting for pr_test_db...';
        until psql postgres://postgres:pr_password@db:5432/pr_test_db?sslmode=disable -c '\\q' >/dev/null 2>&1; do sleep 1; done;
        echo '🧪 Running integration tests...';
        go test ./... -tags=integration -v
      "

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr_management_app
    environment:
      HTTP_ADDRESS: ":8080"
      DB_URL: "postgres://postgres:pr_password@db:5432/pr_db?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres-data:
